---
- name: Edit UserDefault
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ osx_defaults }}"

- name: Mute sound volume
  shell: osascript -e "set Volume 0"
  ignore_errors: true
