---
osx_defaults:
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true

  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15

  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2