---
osx_defaults:
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    
  - domain: com.apple.dock    
    key: tilesize
    type: float
    value: 60
    
  - domain: com.apple.dock    
    key: orientation
    type: string
    value: "bottom"  
    
  - domain: com.apple.menuextra.battery    
    key: ShowPercent
    type: string
    value: "YES"  

  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15

  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
