---
osx_defaults:
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    
  - domain: com.apple.dock    
    key: tilesize
    type: float
    value: 60
    
  - domain: com.apple.dock    
    key: orientation
    type: string
    value: "bottom"  

  - domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "clmv"

  - domain: com.apple.finder
    key: NewWindowTarget
    type: string
    value: "PfHm"

  - domain: com.apple.finder
    key: NewWindowTargetPath
    type: string
    value: "file://${HOME}/"

  - domain: com.apple.menuextra.battery    
    key: ShowPercent
    type: string
    value: "YES"

  - domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "M\u6708d\u65e5(EEE)  H:mm:ss"

  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

  - domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 15

  - domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 2
