#+TITLE: Overview
#+TEXT: Create: 2013-09-16
#+TEXT: Last Update: 2024-01-28
#+STARTUP: showall
#+OPTIONS: \n:t

The script to automatically build my development environment.

Keyword: macOS, Xcode, Homebrew, Emacs, Zsh

* Usage
** Nix-based setup (macOS + WSL)
- Update =nix/hosts.nix= for your username and host names.
- Install Nix (flakes enabled).
- macOS: install =nix-darwin= and apply the flake.
  #+begin_src sh
  darwin-rebuild switch --flake .#<darwinHost>
  brew bundle --file brew/Brewfile
  #+end_src
- WSL (Ubuntu): install =home-manager= and apply the flake.
  #+begin_src sh
  home-manager switch --flake .#<username>@<wslHost>
  #+end_src
- Validate evaluation with flake checks.
  #+begin_src sh
  ./scripts/nix-check.sh
  #+end_src
- Devcontainer check (Linux): runs a disposable apply using the devcontainer host.
  #+begin_src sh
  ./scripts/devcontainer-check.sh
  #+end_src

** GitHub Codespaces
- This repo includes a devcontainer definition at =.devcontainer/devcontainer.json=.
- On first launch, Codespaces runs =./scripts/devcontainer-check.sh= which:
  - runs =nix flake check=
  - applies the Home Manager configuration for =vscode@devcontainer=
- If you don't want your Codespace home directory dotfiles to be managed automatically, remove/disable =postCreateCommand= in =.devcontainer/devcontainer.json= and run the script manually when needed.

** GitHub Codespaces Dotfiles
- You can also use this repository as a Codespaces *Dotfiles* repository.
- When configured in GitHub settings, Codespaces clones this repo and runs =./install.sh=.
- On Linux (Codespaces), =install.sh= installs Nix (if needed) and applies the Home Manager configuration for the current user (e.g. =codespace@devcontainer=).
- Note: this repo uses a git submodule (=resources/zsh/.zsh/zaw=). =install.sh= initializes submodules automatically, but your environment must allow fetching it.

** CI
- GitHub Actions runs =nix flake check= on Ubuntu and macOS for every push and PR.

** Legacy (stow + dotnet-script)
#+begin_src sh
/bin/zsh -c "$(curl -fsSL https://raw.githubusercontent.com/hiroakit/xcclt/HEAD/xcclt.sh)" && git clone https://github.com/hiroakit/profile --recursive && cd profile && sh install.sh
#+end_src

* Requirements
** Nix-based setup
- Nix (flakes enabled)
- nix-darwin (macOS)
- home-manager (WSL)

** Legacy (stow + dotnet-script)
- macOS Sonoma v14.3
- Command Line Tools for Xcode v15.1
- .NET 6
- Homebrew v4.1.25
- GNU Stow v2.3.1

# ** Software dependencies                                           :noexport:
#  
# | software | version                               | source             |
# |----------+---------------------------------------+--------------------|
# | Emacs    | 24.3                                  | [[http://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-24&id=3a1ce0685f66f5fb162b07f6bf4a1d8e1ec75c06][git commit 3a1ce06]] |
# | Zsh      | zsh 5.0.2 (x86_64-apple-darwin12.4.0) | [[http://sourceforge.net/p/zsh/code/ci/zsh-5.0.2/tree/][git commit daa828b]] |
# | rbenv    | 0.4.0-89-g14bc162                     | [[https://github.com/sstephenson/rbenv/commit/14bc162ca606e0c61da8d82e1b99b0946d7be13f][git commit 14bc162]] |
# | iTerm2   | 1.0.0.20140421                        | [[https://github.com/gnachman/iTerm2/commit/4cf1808a903ca5f185f35c4d775f1bd7b4ac4e79][git commit 4cf1808]] |
#  
# If you export a Libra-Office style's document by org-mode, you should install Libra-Office.
#  
# *** How to build Emacs ?
# I will make build script for Emacs.
# This code was including inline-patch.
# #+BEGIN_SRC sh
# $ cd ~/your/working/dir
# $ git clone git://git.savannah.gnu.org/emacs.git
# $ svn co http://svn.sourceforge.jp/svnroot/macemacsjp/inline_patch/trunk inline_patch
# $ cd ~/~/your/working/dir/emacs
# $ ./autogen.sh 
# $ patch -p0 < ../inline_patch/emacs-inline.patch
# $ ./configure --with-ns --without-x --enable-locallisppath=/usr/local/share/emacs/site-lisp <-- may need --without-selinux option
# $ make bootstrap
# $ make install
# $ mv nextstep/Emacs.app /Applications/Emacs.app
# #+END_SRC
#  
# * Emacs                                                            :noexport:
#  
# Plese see emacs.org file.
#  
# * Zsh                                                              :noexport:
#  
# Dependency.
#  
# | library | description                   |
# |---------+-------------------------------|
# | zaw     | Emacs Anything like interface |
#  
# * Profile for Terminal.app                                         :noexport:
#  
# If you use profile, you need to get MigMix 2M.
#  
# MigMixフォント : M+とIPAの合成フォント
# http://mix-mplus-ipa.osdn.jp/migmix/
#  
# * PGP                                                              :noexport:
#  
# In macOS, using MacGPG that is engine of [[https://gpgtools.org/][GPG Suite]] as PGP software.
