---

# Defined items
# See ../roles/homebrew/default/main.yml

- name: Add homebrew taps
  homebrew_tap:
    tap: "{{ item.tap }}"
    state: present
  with_items:
    - "{{ homebrew_taps }}"
    
- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Install homebrew packages
  homebrew:
    name="{{ item.name | default(item) }}"
    state="{{ item.state | default('present') }}"
    install_options="{{ item.install_option | default('') }}"
  with_items: "{{homebrew_packages}}"
  when: homebrew_packages

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ homebrew_cask_packages }}"
