---
- name: create .emacs.d symlink
  file: src=~/documents/sources/profile/resources/emacs dest=~/.emacs.d state=link
  tags:
    - dotfiles

- name: create .zsh symlink
  file: src=~/documents/sources/profile/resources/zsh dest=~/.zsh state=link
  tags:
    - dotfiles

- name: create .zshenv symlink
  file: src=~/documents/sources/profile/resources/zsh/.zshenv dest=~/.zshenv state=link
  tags:
    - dotfiles
