---
- name: Create downloads directory
  file:
    path=~/src/profile/provisioning/downloads
    state=directory

- name: Download MigMix 2M
  get_url:
    url=https://osdn.jp/frs/redir.php?m=jaist&f=%2Fmix-mplus-ipa%2F63544%2Fmigmix-2m-20150712.zip
    dest=~/src/profile/provisioning/downloads
    sha256sum=a8639f277f5a2a2c78c20d05d2a6fb0977116193dcb708997a04080e9615882d
    force=True

- name: Unzip MigMix 2M
  unarchive:
    src=~/src/profile/provisioning/downloads/migmix-2m-20150712.zip
    dest=~/src/profile/provisioning/downloads/

- name: Copy MigMix 2M - migmix-2m-bold.ttf
  copy:
    src=~/src/profile/provisioning/downloads/migmix-2m-20150712/migmix-2m-bold.ttf
    dest=~/Library/Fonts/migmix-2m-bold.ttf

- name: Copy MigMix 2M - migmix-2m-regular.ttf
  copy:
    src=~/src/profile/provisioning/downloads/migmix-2m-20150712/migmix-2m-regular.ttf
    dest=~/Library/Fonts/migmix-2m-regular.ttf